<a href="https://colab.research.google.com/github/Deepsphere-AI/DataAnalyticsTrainingBatch4/blob/main/Python/TeachingFiles/LVA_DSAI_Unit_2_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## NumPy is a Python library.
## NumPy is used for working with arrays.
## NumPy is short for "Numerical Python".
###~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 1 - Simple Example
#~~~~~~~~~~~~~~~~~~~~~~~~~
import numpy
vAR_arr = numpy.array([1,2,3,4,5]) ## Array based on a List
#print(vAR_arr)

#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 2 - Checking NumPy Version
#~~~~~~~~~~~~~~~~~~~~~~~~~
#print("<< Example 2 Checking NumPy Version >>")

import numpy as np ## See the import statement above

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(np.__version__ + "   << Numby Version")

[1 2 3 4 5]
1.25.2   << Numby Version


In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 3 - Create a NumPy ndarray Object - Array Type
#~~~~~~~~~~~~~~~~~~~~~~~~~
print("<< Example 3 Create a NumPy ndarray Object >>")
import numpy as np
arr = np.array([1, 2, 3, 4, 5,"JOTHI"]) ## Does this array may give an error since it has a String.
print(arr)
print(type(arr)) ##  N-dimensional array (ndarray)

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 4 - Use a tuple to create a NumPy array:
#~~~~~~~~~~~~~~~~~~~~~~~~~
print("<< Example 4 Use a tuple to create a NumPy array: >>")
import numpy as np
arr = np.array((1, 2, 3, 4, 5)) ## Array based on Tuple
print(arr)

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 5 - NumPy Array Indexing: +Access Array Elements
#~~~~~~~~~~~~~~~~~~~~~~~~~
print("<< Example 5 NumPy Array Indexing: + Access Array Elements >>")
import numpy as np
arr = np.array([111, 121, 200, 300])
print(arr)
print(arr[0])
print(arr[1])
print(arr[2] + arr[3]) ## Adding two elements

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 6 - NumPy Array Slicing
# We pass slice instead of index like this: [start:end].
# We can also define the step, like this: [start:end:step].
#~~~~~~~~~~~~~~~~~~~~~~~~~
print("<< Example 6 NumPy Array Slicing >>")
import numpy as np
arr = np.array([111, 222, 333, 444, 555, 666, 777])

print(arr[1:3]) #slice elements from index 1 to index 3 (not included):
print(arr[4:]) #slice elements from index 4th to end
print(arr[:4]) #slice elements from index 0 to index 4 (not included):
print(arr[-3:-1]) # Negative Slicing - Slice from the index 3 from the end to index 1 from the end:
print(arr[1:5:2]) #STEP - Return every other element from index 1 to index 5:
print(arr[::2]) # Return every other element from the entire array:
arr[:]=999 ### What this function does?
print(arr)

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 7 - Slicing 2-D Arrays
#~~~~~~~~~~~~~~~~~~~~~~~~~
print("<< Example 7 Slicing 2-D Arrays >>")
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#print(arr)
#print(arr[1, 1:4]) # From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2])  # From both elements, return index 2:

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 8 - Data Types in NumPy
#~~~~~~~~~~~~~~~~~~~~~~~~~
## i - integer , ## b - boolean , ## u - unsigned integer , ## f - float , ## c - complex float
## m - timedelta , ## M - datetime ,  ## O - object
## S - string, ## U - unicode string, ## V - fixed chunk of memory for other type ( void )
print("<< Example 8 Data Types in NumPy >>")
import numpy as np
arr = np.array(['1.1', 2.2, 3.3, 4])
#print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
#print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='f') # Create an array with data type string:
#print(arr) # What is the outcome and why it prints in such a way
#print(arr.dtype)

arr = np.array([1, 2, 3, 4], dtype='S') # Create an array with data type 4 bytes integer:
print(arr)
print(arr.dtype)

<< Example 8 Data Types in NumPy >>
[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 9 - Data Types in NumPy
#~~~~~~~~~~~~~~~~~~~~~~~~~

print("<< Example 9 Change data type from float to integer by using 'i' as parameter value: >>")
import numpy as np
arr = np.array([1.1, 2.1, 3.1])
#print(arr.dtype)
newarr = arr.astype('i') # Change data type from float to integer by using 'i' as parameter value:
#print(newarr)
#print(newarr.dtype)
newarr = arr.astype(int) # Change data type from float to integer by using int as parameter value:
print(newarr)
print(newarr.dtype)

<< Example 9 Change data type from float to integer by using 'i' as parameter value: >>
[1 2 3]
int64


In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 10 - Change data type from integer to boolean::
#~~~~~~~~~~~~~~~~~~~~~~~~~

print("<< Example 10 Change data type from integer to boolean: >>")
import numpy as np
arr = np.array([1, 0, 13])
newarr = arr.astype(bool) # Change data type from integer to boolean::
print(newarr) # What is the expected outcome and why it is so
print(newarr.dtype)

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 11 - Copy and View
#~~~~~~~~~~~~~~~~~~~~~~~~~
print("<< Example 11 Change data type from integer to boolean: >>")
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 999999 # Changing the copy
#print("COPY-Original", arr) # Original Array
#print("Copy", x) # Copy

y = arr.view() # Make a view, change the original array, and display both arrays:
arr[0] = 42 # Changing the view
print("VIEW-Original", arr) # Original Array
print("VIEW",y) # View


In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 12 - Check if Array "Owns" its Data
#~~~~~~~~~~~~~~~~~~~~~~~~~
print("<< Example 12 Change data type from integer to boolean: >>")
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base) # since this is a copied and a seperate data by itself, there is nothig in the base for "X"
print(x)
#print(y.base)
#print(y)
## The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
## The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 13 - Shape of an Array: The shape of an array is the number of elements in each dimension.
#~~~~~~~~~~~~~~~~~~~~~~~~~
print("<< Example 13 Shape of an Array: The shape of an array is the number of elements in each dimension. >>")
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]) # Print the shape of a 2-D array:
print(arr.shape) # Print the shape of a 2-D array:

arr = np.array([1, 2, 3, 4], ndmin=5)
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:
#print(arr)
#print('shape of array :', arr.shape)


In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 14 - Reshape
#~~~~~~~~~~~~~~~~~~~~~~~~~
import numpy as np
arr = np.array([111, 222, 333, 444, 555, 666, 777, 888])
#newarr = arr.reshape(3, 3) # converting 1D array with 8 elements to a 2D array with 3 elements in each dimension
#print(newarr)
newarr = arr.reshape(2, 4) # converting 1D array with 8 elements to a 2D array with 3 elements in each dimension
print(newarr)

[[111 222 333 444]
 [555 666 777 888]]


In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 14 - Reshape
#~~~~~~~~~~~~~~~~~~~~~~~~~
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) # Reshape From 1-D to 2-D
newarr = arr.reshape(3, 4) #?????
#print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]) # Reshape From 1-D to 3-D
newarr = arr.reshape(2, 3, 2) #?????
print(newarr)

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 15 - Reshape  Convert the array into a 1D array:
#~~~~~~~~~~~~~~~~~~~~~~~~~
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1) # Convert the array into a 1D array:
print(newarr)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) # Convert 1D array with 8 elements to 3D array
newarr = arr.reshape(1, 8, -1) # Convert 1D array with 8 elements to 3D array
print(newarr)

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 15 - Iterating Arrays
#~~~~~~~~~~~~~~~~~~~~~~~~~
import numpy as np

arr = np.array([1, 2, 3]) #Iterate on the elements of the following 1-D array
for x in arr:
  print(x)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #Iterating 3-D Arrays
for x in arr:
  print(x)

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 16 - Iterate on each scalar element of the 2-D array:
#~~~~~~~~~~~~~~~~~~~~~~~~~
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]]) # Iterate on each scalar element of the 2-D array:
#print(arr)
for x in arr:
  for y in x:
    print(y)

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 17 - Joining NumPy Arrays
#~~~~~~~~~~~~~~~~~~~~~~~~~
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2)) #Joining NumPy Arrays
#print(arr)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2),axis=0) #Join two 2-D arrays along rows (axis=1)
print(arr)
arr = np.concatenate((arr1, arr2),axis=-1) #Join two 2-D arrays along rows (axis=1)
#print(arr)

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 18 - Splitting NumPy Arrays
#~~~~~~~~~~~~~~~~~~~~~~~~~
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3) #Split the array in 3 parts:
print(newarr)

newarr = np.array_split(arr, 4) #Split the array in 4 parts:
#print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 19 - NumPy Searching Arrays
#~~~~~~~~~~~~~~~~~~~~~~~~~
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4]) #Find the indexes where the value is 4:
x = np.where(arr == 4) #Find the indexes where the value is 4:
#print(x)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) #Find the indexes where the values are even:
x = np.where(arr%2 == 0) #Find the indexes where the values are even:
#print(x)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) #Find the indexes where the values are odd:
x = np.where(arr%2 == 1) #Find the indexes where the values are odd:
print(x)

In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 20 - Sorting Arrays
#~~~~~~~~~~~~~~~~~~~~~~~~~
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr)) # Sort the array:

arr = np.array(['banana', 'cherry', 'apple']) #Sort the array alphabetically:
print(np.sort(arr))

arr = np.array([True, False, True])
print(np.sort(arr)) #Sort a boolean array:

arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr)) #Sort a 2-D array:



[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]
[[2 3 4]
 [0 1 5]]


In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 21 - NumPy Filter Array
#    Getting some elements out of an existing array and creating a new array out of them is called filtering.
#~~~~~~~~~~~~~~~~~~~~~~~~~
import numpy as np
arr = np.array([41, 42, 43, 44])
y = np.array([False, False, True, False])
#x = [True, False, True, False] #Create an array from the elements on index 0 and 2:
    # If the value at an index is True that element is contained in the filtered array,
    # if the value at that index is False that element is excluded from the filtered array.
#print(arr)
#print(y)
newarr = arr[y] # Filtered Values
print(newarr)

arr = np.array([41, 42, 43, 44])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
#print(filter_arr)
#print(newarr)

[43]


In [ ]:
#~~~~~~~~~~~~~~~~~~~~~~~~~
# NumPy - Example 22 - NumPy - Broadcasting
#    The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations.
#     Assignment : How the operations on arrays of non-similar shapes is still possible in NumPy
#~~~~~~~~~~~~~~~~~~~~~~~~~

import numpy as np
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print(c)

#a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0]]) ## Practice Exercise/Homework
#b = np.array([1.0,2.0,3.0]) ## Practice Exercise/Homework

#print('First array:')
#print(a)
#print ('\n')

#print ('Second array:')
#print (b )
#print('\n')

print ('First Array + Second Array' )
print (a + b)
print (a * b)
print (a - b)

[ 10  40  90 160]
First Array + Second Array
[11 22 33 44]
