<a href="https://colab.research.google.com/github/Deepsphere-AI/DataAnalyticsTrainingBatch4/blob/main/Python/Answers%20for%20IA2/Key_for_IA2_of_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Q1

import numpy as np

def rgb_to_grayscale(rgb_image):
    # Ensure input is a NumPy array
    rgb_image = np.array(rgb_image)

    # Check if the array has three dimensions (height, width, RGB channels)
    if rgb_image.ndim != 3 or rgb_image.shape[2] != 3:
        raise ValueError("Input should be a 3D NumPy array representing an RGB image")

    # Apply the luminosity method to convert RGB to grayscale
    grayscale_image = np.dot(rgb_image, [0.2989, 0.5870, 0.1140])

    return grayscale_image

# Example usage:
rgb_image = np.array([[[255, 0, 0], [0, 255, 0], [0, 0, 255]],
                      [[255, 255, 0], [255, 0, 255], [0, 255, 255]],
                      [[127, 127, 127], [200, 200, 200], [50, 50, 50]]])

grayscale_image = rgb_to_grayscale(rgb_image)
print(grayscale_image)

[[ 76.2195 149.685   29.07  ]
 [225.9045 105.2895 178.755 ]
 [126.9873 199.98    49.995 ]]


In [2]:
#Q2

import numpy as np

def normalize_attributes(data):
    # Calculate the mean and standard deviation along the attribute axis (axis 0)
    mean = np.mean(data, axis=0)
    std_dev = np.std(data, axis=0)

    # Apply normalization formula: (x - mean) / std_dev
    normalized_data = (data - mean) / std_dev

    return normalized_data

# Example usage:
# Assuming data is a multidimensional NumPy array with attributes like height, weight, age
data = np.array([[160, 60, 25],
                 [170, 65, 30],
                 [180, 70, 35]])

normalized_data = normalize_attributes(data)
print("Normalized data:")
print(normalized_data)


Normalized data:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


In [3]:
#Q3
import numpy as np

def reorganize_sensor_data(data):
    # Get the shape of the input data
    num_sensors, rows, cols = data.shape

    # Flatten the data from each sensor
    flattened_data = data.reshape(num_sensors, -1)

    # Reshape the flattened data so that each sensor's data forms a single row
    reorganized_data = flattened_data.reshape(num_sensors, -1)

    return reorganized_data

# Example usage:
# Suppose sensor_data is a 3D NumPy array representing data collected from multiple sensors
sensor_data = np.array([[[1, 2, 3],
                         [4, 5, 6]],
                        [[7, 8, 9],
                         [10, 11, 12]],
                        [[13, 14, 15],
                         [16, 17, 18]]])

reorganized_data = reorganize_sensor_data(sensor_data)
print("Reorganized data:")
print(reorganized_data)

Reorganized data:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [4]:
#Q4
import numpy as np

def calculate_improvement(scores):
    # Get the number of athletes (rows) and number of games (columns)
    num_athletes, num_games = scores.shape

    # Index the scores of the first and last games for each athlete
    first_game_scores = scores[:, 0]  # Indexing the first column
    last_game_scores = scores[:, -1]   # Indexing the last column

    # Compute the improvement for each athlete
    improvement = last_game_scores - first_game_scores

    return improvement

# Example usage:
# Assuming scores is a 2D NumPy array where each row represents an athlete's performance scores
scores = np.array([[10, 15, 20, 25],
                   [12, 18, 22, 30],
                   [8, 14, 16, 18]])

improvement = calculate_improvement(scores)
print("Improvement in performance for each athlete:")
print(improvement)

Improvement in performance for each athlete:
[15 18 10]


In [5]:
#Q5
import numpy as np

def calculate_average_last_three_subjects(scores):
    # Slice the array to include only the last three subjects for each student
    last_three_subjects_scores = scores[:, -3:]

    # Filter out the scores marked as 'exempt' (-1)
    valid_scores = np.ma.masked_equal(last_three_subjects_scores, -1)

    # Compute the average for each student
    average_scores = valid_scores.mean(axis=1)

    return average_scores

# Example usage:
# Assuming scores is a 2D NumPy array where each row represents a student's scores in various subjects
scores = np.array([[80, 90, 85, -1, 92],
                   [70, 75, -1, 85, 88],
                   [88, 82, 90, 92, 95]])

average_last_three_subjects = calculate_average_last_three_subjects(scores)
print("Average score in the last three subjects for each student:")
print(average_last_three_subjects)

Average score in the last three subjects for each student:
[88.5 86.5 92.33333333333333]


In [6]:
#Q6
import numpy as np

def apply_monthly_adjustments(city_temperatures, adjustment_factors):
    # Ensure both arrays have compatible shapes for broadcasting
    if city_temperatures.shape[1] != adjustment_factors.shape[0]:
        raise ValueError("Number of months in city temperatures array does not match adjustment factors array")

    # Apply adjustments using broadcasting
    adjusted_temperatures = city_temperatures + adjustment_factors

    return adjusted_temperatures

# Example usage:
# Assuming city_temperatures is a 2D NumPy array and adjustment_factors is a 1D NumPy array
city_temperatures = np.array([[20, 25, 30, 22],
                               [18, 22, 28, 20],
                               [15, 20, 25, 18]])

adjustment_factors = np.array([1.5, 2.0, 1.0, 1.2])

adjusted_temperatures = apply_monthly_adjustments(city_temperatures, adjustment_factors)
print("Adjusted temperatures:")
print(adjusted_temperatures)

Adjusted temperatures:
[[21.5 27.  31.  23.2]
 [19.5 24.  29.  21.2]
 [16.5 22.  26.  19.2]]


In [7]:
#Q7
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'],
        'Age': [25, 30, 35, 40, 45, 50, 55],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Miami', 'Boston'],
        'Department': ['HR', 'IT', 'Finance', 'Marketing', 'Sales', 'IT', 'HR']}

# Convert data to a pandas DataFrame for easier manipulation
import pandas as pd
df = pd.DataFrame(data)

# Filter employees under 45 who are not in the HR department
filtered_df = df[(df['Age'] < 45) & (df['Department'] != 'HR')]

# Extract names and cities of the filtered employees
employees_list = filtered_df[['Name', 'City']].values.tolist()

print("List of employees under 45 not in HR department:")
print(employees_list)

List of employees under 45 not in HR department:
[['Bob', 'Los Angeles'], ['Charlie', 'Chicago'], ['David', 'Houston']]


In [8]:
#Q8
import pandas as pd

# Create DataFrame from the given data
data = {
    'Product': ['Apples', 'Bananas', 'Cherries', 'Dates', 'Elderberries', 'Flour', 'Grapes'],
    'Category': ['Fruit', 'Fruit', 'Fruit', 'Fruit', 'Fruit', 'Bakery', 'Fruit'],
    'Price': [1.20, 0.50, 3.00, 2.50, 4.00, 1.50, 2.00],
    'Promotion': [True, False, True, True, False, True, False]
}

df = pd.DataFrame(data)

# Filter products from the 'Fruit' category
fruit_df = df[df['Category'] == 'Fruit']

# Calculate the average price for the 'Fruit' category
average_price_fruit = fruit_df['Price'].mean()

# Identify products that are both above average price and not part of any promotion
potential_promotions = fruit_df[(fruit_df['Price'] > average_price_fruit) & (~fruit_df['Promotion'])]

print("Potential candidates for future promotions:")
print(potential_promotions)

Potential candidates for future promotions:
        Product Category  Price  Promotion
4  Elderberries    Fruit    4.0      False


In [9]:
#Q9
import pandas as pd

# Define the employee data
employee_data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David'],
    'Department': ['HR', 'IT', 'Finance', 'IT'],
    'Manager': ['John', 'Rachel', 'Emily', 'Rachel']
}

# Define the project data
project_data = {
    'Employee': ['Alice', 'Charlie', 'Eve'],
    'Project': ['P1', 'P3', 'P2']
}

# Create DataFrames from the data
employee_df = pd.DataFrame(employee_data)
project_df = pd.DataFrame(project_data)

# Merge the employee and project data based on the 'Employee' column
merged_df = pd.merge(project_df, employee_df, on='Employee', how='left')

# Fill missing values in 'Department' and 'Manager' columns with appropriate values
merged_df['Department'] = merged_df['Department'].fillna('Unassigned')
merged_df['Manager'] = merged_df['Manager'].fillna('Unassigned')

# Group by department and manager to get an overview of each department's projects
department_overview = merged_df.groupby(['Department', 'Manager'])['Project'].apply(list).reset_index()

print("Departmental Overview:")
print(department_overview)

Departmental Overview:
   Department     Manager Project
0     Finance       Emily    [P3]
1          HR        John    [P1]
2  Unassigned  Unassigned    [P2]


In [10]:
#Q10
import pandas as pd

data = {
    'Department': ['Electronics', 'Electronics', 'Clothing', 'Clothing', 'Home Goods'],
    'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Sales': [70000, 50000, 30000, 40000, 60000]
}

# Create a DataFrame from the data
df = pd.DataFrame(data)

# Calculate total sales per department
department_sales = df.groupby('Department')['Sales'].sum()

# Count the number of salespeople in each department
department_salespeople_count = df.groupby('Department')['Salesperson'].size()

# Calculate average sales per salesperson in each department
average_sales_per_salesperson = department_sales / department_salespeople_count

# Rank the departments based on their average sales
ranked_departments = average_sales_per_salesperson.sort_values(ascending=False).reset_index()

# Add salespeople count to the ranked departments DataFrame
ranked_departments['Salespeople Count'] = department_salespeople_count.reset_index(drop=True)

print("Ranked Departments based on Average Sales per Salesperson:")
print(ranked_departments)

Ranked Departments based on Average Sales per Salesperson:
    Department        0  Salespeople Count
0  Electronics  60000.0                  2
1   Home Goods  60000.0                  2
2     Clothing  35000.0                  1
